### ISSUE TITLE
Issue with level editing in saves.

### ISSUE THREAD

**Issue by UnableUser** [MrMarble/drg-editor#27]
I tried the save editor however I ran into an issue. 
Editing only the resource values worked fine for me, save loaded and did fine.
However as soon as I edit the dwarf levels the game resets the save (I'm guessing because it went corrupt).

**Comment by PretzelXDD** [comment]
Will it ever be fixed? I hope so.

**Comment by MrMarble** [comment]
Yes it will, I was on vacations, it's open source, so anyone can fix it if they want...
Will upload a fix soon.

related to #34
