### ISSUE TITLE
Promotion display error

### ISSUE THREAD

**Issue by JingShing** [MrMarble/drg-editor#34]
Character promotion is wrong. My engineer and driller is bronze the others are none but it will display bronze or none randomly for every character when I switch page between characters.

**Comment by meechgalhuquot** [comment]
I have the same issue, and if I try changing any character parameters (haven't touched overclocks yet) it starts up in the tutorial mission with 0 game progress at all with the save file I get

**Comment by MrMarble** [comment]
You are right, it seems I made a mistake in one of the changes I made causing react to not render the component correctly, carrying the state between the different dwarfs.
I will upload a fix soon.
